config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :points do
    resources :stations do
      resources :connectors
    end
  end
  resources :sessions, only: [:index, :create, :show]
  post 'sessions/:id/stop', to: 'sessions#stop'
  match 'sessions/:id/stop', to: 'sessions#stop', via: 'post', as: 'session_stop'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sessions, dependent: :destroy

  validates_presence_of :full_name, :phone_number
  validates_uniqueness_of :phone_number

  def get_active
    self.sessions.where(status: 'active')
  end
  def is_free?
    self.get_active.empty?
  end
end

app/models/connector.rb
class Connector < ApplicationRecord
  belongs_to :station
  has_many :sessions, dependent: :destroy

  valid_types = ['CHAdeMO', 'CCS Combo 2', 'Type 2']

  validates :power, presence: true, numericality: {greater_than: 0}
  validates :connector_type, presence: true, inclusion: { in: valid_types }
  def get_active
    self.sessions.where(status: 'active')
  end
  def is_free?
    self.get_active.empty?
  end
end

app/models/point.rb
class Point < ApplicationRecord
  has_many :station, dependent: :destroy

  validates_presence_of :name, :latitude, :longitude
  validates_uniqueness_of :name
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :client
  belongs_to :connector

  valid_statuses = %w[active disable]

  validates :status, presence: true, inclusion: { in: valid_statuses }
  validates :energy, presence: true, numericality: { greater_than: 0 }
  validate :check_connector, :check_client

  private
  def check_connector
    if status == 'active'
    connector = Connector.find(connector_id)
    unless connector.is_free?
      sessions = connector.get_active
      sessions.each do |session|
        unless session.id == self.id
          errors.add( :connector_id, "must be free")
        end
      end
    end
    end
  end

  def check_client
    if status == 'active'
    client = Client.find(client_id)
    unless client.is_free?
      sessions = client.get_active
      sessions.each do |session|
        unless session.id == self.id
          errors.add( :client_id, "must be free")
        end
      end
    end
    end
  end

end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :point
  has_many :connectors, dependent: :destroy

  validates :serial_number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/connectors_controller.rb
class ConnectorsController < ApplicationController
  before_action :set_point_and_station
  before_action :set_connector, except: [:new, :create]
  def show
    if @connector.is_free?
      @session = @connector.sessions.build
    else
      @session = @connector.get_active.first
    end
  end
  def new
    @connector = @station.connectors.new
  end

  def create
    @connector = @station.connectors.create connector_params
    if @connector.save
      redirect_to point_station_path(@point, @station)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @connector.update connector_params
      redirect_to point_station_connector_path(@point, @station, @connector)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @connector.destroy

    redirect_to point_station_path(@point, @station)
  end

  private
  def connector_params
    params.require(:connector).permit(:connector_type, :power)
  end

  def set_point_and_station
    @point = Point.find(params[:point_id])
    @station = Station.find(params[:station_id])
  end

  def set_connector
    @connector = Connector.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @points = Point.all
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
    @points = Point.all
    stations_json, points_json = {}
    @points.each do |point|
      stations = Station.where(point_id: point[:id])
      stations.each do |station|
        connectors = Connector.where(station_id: station[:id]).to_json
        stations_json = station.to_json, connectors
      end
      points_json = point.to_json, stations_json
    end
    render json: points_json
  end

  def show
    @point = Point.find(params[:id])
    @stations = @point.station.all
  end

  def new
    @point = Point.new
  end

  def create
    @point = Point.new point_params

    if @point.save
      redirect_to points_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @point = Point.find(params[:id])
  end

  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    redirect_to root_path, status: :see_other
  end

  def update
    @point = Point.find(params[:id])

    if @point.update(point_params)
      redirect_to points_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def point_params
      params.require(:point).permit(:name, :latitude, :longitude)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    @sessions = Session.all

    render json: @sessions
  end

  def show
    @session = Session.find(params[:id])
    @client = Client.find(@session.client_id)
    @point = Point.find(Station.find(Connector.find(@session.connector_id).station_id).point_id)
    render json: { "session": @session,
      "client": [ @client.phone_number, @client.full_name ],
      "point": @point.name }.to_json
  end

  def create
    @session = Session.new session_params
    respond_to do |format|
      if @session.save
        set_back_params
        format.html { redirect_to point_station_connector_path(@point, @station, @connector) }
        format.json { render :show, status: :created, location: @session }
      else
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end
  def stop
    @session = Session.find(params[:id])
    @session.status = 'disable'
    respond_to do |format|
      if @session.save
        set_back_params
        format.html { redirect_to point_station_connector_path(@point, @station, @connector) }
        format.json { render :show, status: :created, location: @session }
      else
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end

  end

  private
  def session_params
    params.require(:session).permit(:client_id, :energy).merge(status: "active", connector_id: params[:connector_id])
  end

  def set_back_params
    @connector = Connector.find(@session.connector_id)
    @station = Station.find(@connector.station_id)
    @point = Point.find(@station.point_id)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_point
  before_action :set_station, except: [:new, :create]
  def show
    @connectors = @station.connectors.all
  end

  def new
    @station = @point.station.new
  end

  def create
    @station = @point.station.create station_params
    if @station.save
      redirect_to point_path(@point)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @station.destroy

    redirect_to point_path(@point), status: :see_other
  end

  def edit
  end

  def update
    if @station.update station_params
      redirect_to point_path @point
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def station_params
    params.require(:station).permit(:serial_number)
  end

  def set_point
    @point = Point.find(params[:point_id])
  end

  def set_station
    @station = Station.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connectors_helper.rb
module ConnectorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/connectors/_form.html.erb
<%= form_with model: [@point, @station, @connector] do |form| %>
  <p>
    <%= form.label :connector_type %><br>
    <%= form.text_field :connector_type %>
  </p>
  <p>
    <%= form.label :power %><br>
    <%= form.text_field :power %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/connectors/edit.html.erb
<h2>Edit a connector:</h2>

<%= render "form", point: @point, station: @station, connector: @connector %>

<br>
<%= link_to 'back', point_station_connector_path(@point, @station, @connector) %>

app/views/connectors/new.html.erb
<h2>Add a connector:</h2>

<%= render "form", point: @point, station: @station, connector: @connector %>

<br>
<%= link_to 'back', point_station_path(@point, @station) %>

app/views/connectors/show.html.erb
<h1><%= 'Connector' %></h1>

<p>type: <%= @connector.connector_type %></p>
<p>power: <%= @connector.power %></p>

<%= link_to 'edit', edit_point_station_connector_path %>
<%= link_to 'destroy', point_station_connector_path(@point, @station, @connector), data: {
  turbo_method: :delete
} %>

<%= link_to 'back', point_station_path(@point, @station) %>

<% if @connector.is_free? %>
  <h2>No active session</h2>
  <%= render "sessions/form", connector: @connector, session: @session %>
<% else %>
  <h2>Active session:</h2>
  <%= "Session id:#{@session.id}, client id:#{@session.client_id}, energy: #{@session.energy}"  %>
  <%= button_to "Stop active session", session_stop_path(@session), method: :post %>
  <%= link_to 'Show session', session_path(@session) %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Electrocars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= link_to 'sessions', sessions_path %>
<%= link_to 'points', points_path %>
<h1>Points list:</h1>

<ul>
  <% @points.each do |point| %>
    <li>
      <%= link_to point.name, point %>
    </li>
  <% end %>
</ul>

<%= link_to "New Point", new_point_path %>

app/views/points/_form.html.erb
<%= form_with model: @point do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :latitude %><br>
    <%= form.text_area :latitude %>
  </div>

  <div>
    <%= form.label :longitude %><br>
    <%= form.text_area :longitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Edit Point</h1>

<%= render "form", point: @point %>

<br>
<%= link_to 'back', @point %>

app/views/points/index.html.erb
<%= link_to 'sessions', sessions_path %>
<h1>Points list:</h1>

<ul>
  <% @points.each do |point| %>
    <li>
      <%= link_to point.name, point %>
    </li>
  <% end %>
</ul>

<%= link_to "New Point", new_point_path %>

app/views/points/new.html.erb
<h1>New Point</h1>

<%= render "form", point: @point %>

<br>
<%= link_to 'back', root_path %>

app/views/points/show.html.erb
<h1><%= @point.name %></h1>

<p>latitude: <%= @point.latitude %></p>
<p>longitude: <%= @point.longitude %></p>

<%= link_to 'edit', edit_point_path %>
<%= link_to 'destroy', @point, data: {
  turbo_method: :delete
} %>

<%= link_to 'back', root_path %>

<h2>Stations:</h2>
<% @stations.reverse_each do |station| %>
  <li>
  <%= link_to "Station ##{station.serial_number}", point_station_path(@point, station) %>
  </li>
<% end %>
<br>
<%= link_to "New station", new_point_station_path(@point) %>

app/views/stations/_form.html.erb
<%= form_with model: [@point, @station] do |form| %>
  <p>
    <%= form.label :serial_number %><br>
    <%= form.text_field :serial_number %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/stations/edit.html.erb
<h2>Edit a station:</h2>

<%= render "form", point: @point, station: @station %>

<br>
<%= link_to 'back', point_station_path(@point, @station) %>

app/views/stations/new.html.erb
<h2>Add a station:</h2>

<%= render "form", point: @point, station: @station %>

<br>
<%= link_to 'back', point_path(@point) %>

app/views/stations/show.html.erb
<h1><%= "Station##{@station.serial_number}" %></h1>

<%= link_to 'edit', edit_point_station_path %>
<%= link_to 'destroy', point_station_path(@point, @station), data: {
  turbo_method: :delete
} %>

<%= link_to 'back', point_path(@point) %>

<h2>Connectors:</h2>
<% @connectors.reverse_each do |connector| %>
  <li>
    <%= link_to "Type: #{connector.connector_type}, power: #{connector.power}", point_station_connector_path(@point, @station, connector) %>
  </li>
<% end %>
<br>
<%= link_to "New connector", new_point_station_connector_path(@point, @station) %>